// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0iMU7jD9_4APnfWbrP7U0G3o_H3kXUzU',
    appId: '1:378683067383:web:9550252e65bd47427dbcf2',
    messagingSenderId: '378683067383',
    projectId: 'flutterwordgame',
    authDomain: 'flutterwordgame.firebaseapp.com',
    storageBucket: 'flutterwordgame.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkyGvxp-LGncNoghZQF3waMdDymej5DXw',
    appId: '1:378683067383:android:9cb6c09d76d00f957dbcf2',
    messagingSenderId: '378683067383',
    projectId: 'flutterwordgame',
    storageBucket: 'flutterwordgame.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbljaJePtGzK_qnjgPfP9uHoELCioGz4o',
    appId: '1:378683067383:ios:91de1fac575b24f57dbcf2',
    messagingSenderId: '378683067383',
    projectId: 'flutterwordgame',
    storageBucket: 'flutterwordgame.firebasestorage.app',
    iosBundleId: 'com.example.flutterWordGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbljaJePtGzK_qnjgPfP9uHoELCioGz4o',
    appId: '1:378683067383:ios:91de1fac575b24f57dbcf2',
    messagingSenderId: '378683067383',
    projectId: 'flutterwordgame',
    storageBucket: 'flutterwordgame.firebasestorage.app',
    iosBundleId: 'com.example.flutterWordGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0iMU7jD9_4APnfWbrP7U0G3o_H3kXUzU',
    appId: '1:378683067383:web:1a4b42378d9e61697dbcf2',
    messagingSenderId: '378683067383',
    projectId: 'flutterwordgame',
    authDomain: 'flutterwordgame.firebaseapp.com',
    storageBucket: 'flutterwordgame.firebasestorage.app',
  );

}